INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Vanquisher of the Dreg","Adventures : The Malgrave Trail : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Vanquisher of the Samu-Samu","Adventures : War of the Wilds : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Spin to Win","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Sentinel","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Astrovoid Survivalist","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("The Little Engineer That Couldn't","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Good Vibrations","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Feelin' Amped","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("No Mind Games","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Riot Master","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("And Stay Out!","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Survivalist","Adventures : The Malgrave Trail : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Trailhand","Adventures : The Malgrave Trail : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Adventure Discovery: Riot in the Void","Adventures : Riot in the Void");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Brain Freeze","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Vanquisher of Underworld","Adventures : Crimelords of Whitevale : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Whitevale Speedster","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Scrapped","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Yardbird","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Circuit Breaker","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Against the Elements","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Not Sneaky Enough...","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("I Love it When a Plan Falls Apart","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Whitevale Survivalist","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Trailmaster","Adventures : The Malgrave Trail : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Big Man Go Boom","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Mental Muscle","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Vanquisher of FCON","Adventures : The Siege of Tempest Refuge : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("It's All in Your Head","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Jailor","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Warden","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Skeech Master","Adventures : War of the Wilds : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("You're Fired!","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Head of the Snake","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("War of the Wilds Survivalist","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Rebel","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Shoot First, Shoot Last","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Cunning Stroke","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("No Need to Tank Me","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Caravan Leader","Adventures : The Malgrave Trail : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Kiss of Death","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Blood Brother","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Humanitarian Effort","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Decorated Veteran","Adventures : The Siege of Tempest Refuge : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Guardian","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Caravan Master","Adventures : The Malgrave Trail : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Revolutionary","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Capo","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Freedom Fighter","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Adventure Discovery: The Malgrave Trail","Adventures : The Malgrave Trail");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Down with the Ship","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Tempest Refuge Survivalist","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Hycrest Speedster","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("No Need to Tank Me","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Tempest Refuge Speedster","Adventures : The Siege of Tempest Refuge : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Adventure Discovery: The War of the Wilds","Adventures : War of the Wilds");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bad Medicine","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Watch Your Back!","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Brains of the Operation","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Whitevale Speedster","Adventures : Crimelords of Whitevale : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran War of the Wilds Speedster","Adventures : War of the Wilds : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Guerilla","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran War of the Wilds Survivalist","Adventures : War of the Wilds : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Crimelord","Adventures : Crimelords of Whitevale : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Friend of Ours","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Hycrest Survivalist","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Get Out!","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Trailhand","Adventures : The Malgrave Trail : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Crimelord","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Don","Adventures : Crimelords of Whitevale : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gangbuster","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Siege Master","Adventures : The Siege of Tempest Refuge : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Astrovoid Speedster","Adventures : Riot in the Void : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Whitevale Survivalist","Adventures : Crimelords of Whitevale : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Guardian","Adventures : The Siege of Tempest Refuge : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Criminal Mastermind","Adventures : Crimelords of Whitevale : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Petty Criminal","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Defender","Adventures : The Siege of Tempest Refuge : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Master of War","Adventures : War of the Wilds : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Rock Solid Relationship","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("War Hero","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Adventure Discovery: The Siege of Tempest Refuge","Adventures : The Siege of Tempest Refuge");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("I Spy","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Pathfinder","Adventures : The Malgrave Trail : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("The Doctor is Out","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Adventure Discovery: The Hycrest Insurrection","Adventures : The Hycrest Insurrection");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Insurrection Master","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Moodie Masher","Adventures : War of the Wilds : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Malgrave Speedster","Adventures : The Malgrave Trail : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Master of War","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Malgrave Survivalist","Adventures : The Malgrave Trail : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Skeech Wrangler","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Malgrave Speedster","Adventures : The Malgrave Trail : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Street Rat","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Levian Bay Speedster","Adventures : Bay of Betrayal");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Best in the Bay","Adventures : Bay of Betrayal");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Adequate Assassin","Adventures : Bay of Betrayal");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Technopath","Adventures : Bay of Betrayal");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Competent Competitor","Adventures : Bay of Betrayal");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Levian Bay Survivalist","Adventures : Bay of Betrayal");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Adventure Discovery: Bay of Betrayal","Adventures : Bay of Betrayal");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Master Ganker","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Adventure Discovery: Crimelords of Whitevale","Adventures : Crimelords of Whitevale");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Good Riddance!","Adventures : War of the Wilds : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Tempest Refuge Speedster","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Trailmaster","Adventures : The Malgrave Trail : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Survivalist","Adventures : The Malgrave Trail : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Criminal","Adventures : Crimelords of Whitevale : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Robocrook","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Defender","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Siege Master","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Closed for Business","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Malgrave Survivalist","Adventures : The Malgrave Trail : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Martial Glory","Adventures : The Hycrest Insurrection : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Diehard","Adventures : The Siege of Tempest Refuge : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("War of the Wilds Speedster","Adventures : War of the Wilds : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Master Criminal","Adventures : Crimelords of Whitevale : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Veteran Tempest Refuge Survivalist","Adventures : The Siege of Tempest Refuge : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Accepting the Challenge","Challenges",4);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Welcome All Challenges","Challenges",2);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Accepting the Challenge","Challenges",1);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Western Grimvault","Challenges : Grimvault");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Welcome All Challenges","Challenges",1);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Illium","Challenges : Illium");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Auroria","Challenges : Auroria");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Ellevar","Challenges : Ellevar");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Tappers!","Challenges : Ellevar");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Welcome All Challenges","Challenges",3);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Farside","Challenges : Farside");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: The Defile","Challenges : The Defile");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Accepting the Challenge","Challenges",3);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Blighthaven","Challenges : Blighthaven");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Whitevale","Challenges : Whitevale");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Grimvault","Challenges : Grimvault");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Wilderrun","Challenges : Wilderrun");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Deradune","Challenges : Deradune");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Up to the Challenge: Malgrave","Challenges : Malgrave");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Accepting the Challenge","Challenges",2);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Contractor, Hardcore","Contracts");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Workaholic","Contracts",2);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Hired Help","Contracts");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Workaholic","Contracts",5);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Workplace Competition","Contracts");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Workaholic","Contracts",1);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Workaholic","Contracts",3);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Workaholic","Contracts",4);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Workaholic","Contracts",6);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Entry Level Work","Contracts");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Service-Minded Employee","Contracts");
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("What Did I Just Eat?","Dungeons : Skullcano Island",4);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Scatter the Swarm","Dungeons : Sanctuary of the Swordmaiden",2);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Zone Defense","Dungeons : Ruins of Kel Voreth",2);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Cosmic Kick 40","Dungeons : Ultimate Protogames : Ultimate Protogames",3);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Pest Control","Dungeons : Ruins of Kel Voreth",3);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Pest Control","Dungeons : Ruins of Kel Voreth",2);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Zone Defense","Dungeons : Ruins of Kel Voreth",1);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Scatter the Swarm","Dungeons : Sanctuary of the Swordmaiden",3);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("What Did I Just Eat?","Dungeons : Skullcano Island",2);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Zone Defense","Dungeons : Ruins of Kel Voreth",3);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("What Did I Just Eat?","Dungeons : Skullcano Island",1);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Scatter the Swarm","Dungeons : Sanctuary of the Swordmaiden",1);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Scatter the Swarm","Dungeons : Sanctuary of the Swordmaiden",4);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("What Did I Just Eat?","Dungeons : Skullcano Island",3);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Cosmic Kick 20","Dungeons : Ultimate Protogames : Ultimate Protogames",2);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Cosmic Kick 10","Dungeons : Ultimate Protogames : Ultimate Protogames",1);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Pest Control","Dungeons : Ruins of Kel Voreth",1);
INSERT INTO wildstar_achievements_d (ach_name,category,tier) VALUES ("Cosmic Kick 80","Dungeons : Ultimate Protogames : Ultimate Protogames",4);
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Skullcano (Rallied Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Sanctuary of the Swordmaiden (Rallied Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dungeon Discovery: Skullcano","Dungeons");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Presto Prototentiary","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Thunderfoot (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Mordechai Redmoon (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Skullcano (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: The Ruins of Kel Voreth (Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Ruins of Kel Voreth (Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Stormtalon's Lair (Rallied Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: Sanctuary of the Swordmaiden (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Vitara's Heart","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: The Ruins of Kel Voreth (Rallied Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stew-Shaman Tugga (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bosun Octog (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: Skullcano (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bone-Dancing With Grond","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Aethros (Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: Skullcano (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Games Going Green","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stew-Shaman Tugga (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bosun Octog (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: The Ruins of Kel Voreth (Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("The Sky is Falling","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Blade-Wind the Invoker (Normal)","Dungeons : Stormtalon's Lair : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stormtalon (Normal)","Dungeons : Stormtalon's Lair : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Stormtalon's Lair (Normal)","Dungeons : Stormtalon's Lair : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: Skullcano (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Spiritmother Selene (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: Sanctuary of the Swordmaiden (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Sanctuary of the Swordmaiden (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Splatter Skipper","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Forgemaster Trogun (Normal)","Dungeons : Ruins of Kel Voreth : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: Stormtalon's Lair (Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Swift Sweeper","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Great Balls of Fire!","Dungeons : Ruins of Kel Voreth");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Mordechai Redmoon (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Grond the Corpsemaker (Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Forgemaster Trogun (Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: Stormtalon's Lair (Normal)","Dungeons : Stormtalon's Lair : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Jump... Jump Around","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Like Starin' at the Sun","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Skullcano Completionist (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silence is Golden","Dungeons : Sanctuary of the Swordmaiden");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Thunderfoot (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stew-Shaman Tugga's Diet","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dungeon Discovery: Stormtalon's Lair","Dungeons : Stormtalon's Lair");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Just Right","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: Stormtalon's Lair (Normal)","Dungeons : Stormtalon's Lair : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Moldwood Overlord Skash (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Rayna Darkspeaker (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Fungus-Free Diet","Dungeons : Skullcano Island");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Can't Hold Us Back","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Ondu Lifeweaver (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Moldwood Overlord Skash (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Rayna Darkspeaker (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Don't Blink","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Sanctuary of the Swordmaiden (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stay Off Target","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Standard","Dungeons");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Slavemaster Drokk (Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Stormtalon's Lair (Normal)","Dungeons : Stormtalon's Lair : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: Stormtalon's Lair (Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Deadringer Shallaos (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bury the Bosun","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: The Ruins of Kel Voreth (Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Skullcano Completionist (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Slavemaster Drokk (Normal)","Dungeons : Ruins of Kel Voreth : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Protogames Star","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: H.M.S. Phineas","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Ultimate Protogames Champion","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: Skullcano (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Sanctuary of the Swordmaiden (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Slick Moves","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Fleet-Footed","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Shard Shirker","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dodge This","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Claustrophobic Skip","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Sky Soaring","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Cosmic Kicker","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: The Squirgnasium","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Clean Sweeper","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Off My Ship","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Institutionalized","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Protoplunge Professional","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Fluffy and Fluzzball","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Binge Eating","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Total Domination","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Multiplied to the Max","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dungeon Discovery: Protogames Academy","Dungeons");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Taking Turns","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Ruins of Kel Voreth Completionist (Normal)","Dungeons : Ruins of Kel Voreth : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Aethros (Normal)","Dungeons : Stormtalon's Lair : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stormchaser","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Ondu Lifeweaver (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("The Fire and the Dark","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dungeon Discovery: The Ruins of Kel Voreth","Dungeons : Ruins of Kel Voreth");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Protostar Petting Zoo","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Spring Cleaning","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Purge","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Break Room","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Internal Affairs","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Jump Around","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Rapid Kicker","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Multi-Cosmic-Kick","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Atychiphobia","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Keen Senses","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Ultimate Proto-Plunger","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Steamed Veggies","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dust Buster","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Doc in the House","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gauntlet Glancer","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Hut-Hut Hike!","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Time to Shine","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Twinkle Toes","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Master of the Elements","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Low Profile","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Rowsdower Round-Up","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Lost and Found Department","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Frenzy Feast","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Tri Burst Bounce","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Intern Disposal Facility 74","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Extra Credit","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Environmentalist","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Chronophobia","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Toxophobia","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Damage Control","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Hanger Is A Lie","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Lightning Reflexes","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Redemption Value","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Squirg Defuser","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Slimy Feast's Feast","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bev-O-Rager","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Speedy Slaughterfest","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Elemental Hospital","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stage Fright","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Undetectable","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Fowl Feast","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("What's In The Box?","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Butterfingers","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Panic Pronto","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Ghost","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Disrupted Devour","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Be The Rowsdower","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Rowsdower Ruckus","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Squirg Farmer","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Overcoming Toxophobia","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Waste Management Professional","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Crystal Catcher","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Splorg Spree","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Out of Order","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Top-notch Teamwork","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Not So Camera Shy","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Survival Seminar Certification","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Celebratory Dancer","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Loyal Customer","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Waste Management Facility","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Shadowstepper","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Protogames Academy","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Tank Trample","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Pest Control Professional","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dust Storm","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gauntlet Gallop","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Disoriented Descent","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Ruins of Kel Voreth Completionist (Veteran)","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Basic Blue Ribbon","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Like Mother Like Daughters","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Overworked","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Tea Time","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Something's Cooking","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Tomorrow Night's Meal","Dungeons : Protogames Academy : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Scrapyard Cleanup","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: Protogames Academy (Veteran)","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Extra Point Professional","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Protogames Academy (Veteran)","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Demon's Stepping Stones","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Graduation Day","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Anti-Matter Matters","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bother the Bots","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Protogames Academy Diploma (Veteran)","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Flameling Finisher","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bomb-O-Tron Blitz","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Protogames Academy (Veteran)","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Crate Royalty","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: Protogames Academy (Veteran)","Dungeons : Protogames Academy : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Survive the Blitzsquirg","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Prototentiary Prowl","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Hit Snooze","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Jabbit Justification","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Monstrosity Massacre","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Employee Cafeteria","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Make It Rain","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Final Review","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Skullcano (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Skullcano (Normal)","Dungeons : Skullcano Island : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Grond the Corpsemaker (Normal)","Dungeons : Ruins of Kel Voreth : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: The Ruins of Kel Voreth (Normal)","Dungeons : Ruins of Kel Voreth : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Ruins of Kel Voreth (Normal)","Dungeons : Ruins of Kel Voreth : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Trogun Man!","Dungeons : Ruins of Kel Voreth : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Blade-Wind the Invoker (Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stormtalon (Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Stormtalon's Lair (Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: Stormtalon's Lair (Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stormtalon's Lair Completionist (Normal)","Dungeons : Stormtalon's Lair : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: The Ruins of Kel Voreth (Normal)","Dungeons : Ruins of Kel Voreth : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Pell Lightning Rod","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Spiritmother Selene (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Deadringer Shallaos (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Bronze Medal: Sanctuary of the Swordmaiden (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Sanctuary of the Swordmaiden (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("The Sound and the Fury","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Defuse the Situation","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Expert Incinerator","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Cosmic Precision","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Patient Secured","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Immortal: The Prototentiary","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Splorg Stepper","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Friend of Crate","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("No Soup For Ya'll","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Caffeinated","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Shut Out","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Protogames Expert","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Protogames Academy Diploma","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Protogames Star","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dungeon Discovery: Ultimate Protogames","Dungeons");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Weathering the Storm","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Taste Tester","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Star Pupil","Dungeons : Protogames Academy : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gold Medal: Skullcano (Veteran)","Dungeons : Skullcano Island : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Stormtalon's Lair Completionist (Veteran)","Dungeons : Stormtalon's Lair : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Sanctuary of the Swordmaiden Completionist (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Gate-guard Drive-by","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Catcher in the Blight","Dungeons : Sanctuary of the Swordmaiden");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Can Crusher","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Fast Feast","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: The Ruins of Kel Voreth (Normal)","Dungeons : Ruins of Kel Voreth : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Medal: Sanctuary of the Swordmaiden (Veteran)","Dungeons : Sanctuary of the Swordmaiden : Veteran Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Cubig Carnage","Dungeons : Ultimate Protogames : Ultimate Protogames");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Dungeon Discovery: Sanctuary of the Swordmaiden","Dungeons : Sanctuary of the Swordmaiden");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Sanctuary of the Swordmaiden Completionist (Normal)","Dungeons : Sanctuary of the Swordmaiden : Normal Mode");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Silver Screening","Dungeons");
INSERT INTO wildstar_achievements_d (ach_name,category) VALUES ("Synchronized Surge","Dungeons : Protogames Academy : Veteran Mode");
